# Uncomment this line to define a global platform for your project
# platform :ios, ‚8.0‘

pod 'SVProgressHUD'
pod 'SDCAlertView'
pod "JNKeychain"
pod 'FastEasyMapping'
pod "AFNetworking", "~> 2.0"

# ignore all warnings from all pods http://stackoverflow.com/questions/13208202/ignore-xcode-warnings-when-using-cocoapods
inhibit_all_warnings!

