# Uncomment this line to define a global platform for your project
# platform :ios, ‚8.0‘

use_frameworks!

pod 'SDWebImage', '~>3.7'
pod 'SVProgressHUD'
pod 'SDCAlertView'
pod "JNKeychain"
pod 'FastEasyMapping'
pod "AFNetworking", "~> 2.0"
pod "MagicalRecord"
pod "CZPicker"
pod 'CRToast', '~> 0.0.7'
pod 'CNPPopupController', '0.3.1'
pod 'Fabric'
pod 'Crashlytics'
pod 'Toast', '~> 3.0'

# ignore all warnings from all pods http://stackoverflow.com/questions/13208202/ignore-xcode-warnings-when-using-cocoapods
inhibit_all_warnings!

